### ISSUE TITLE
import twophase.solver "EOFError: read() didn't return enough bytes"

### ISSUE THREAD

**Issue by jm493** [AndreaFavero71/CUBOTino_base_version#4]
New software install on macOS Ventura
```
(CUBOTino_venv) porta-mac:PC_files johnm$ pip list
Package       Version
------------- --------
numpy         1.23.4
opencv-python 4.6.0.66
pip           22.3.1
pyserial      3.5
RubikTwoPhase 1.0.9
setuptools    65.5.0
wheel         0.37.1

(CUBOTino_venv) porta-mac:PC_files johnm$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.23.4'
>>> import cv2
>>> cv2.__version__
'4.6.0'
>>> import twophase.solver
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnm/3D/CUBOTino_venv/lib/python3.8/site-packages/twophase/solver.py", line 5, in <module>
    import twophase.symmetries as sy
  File "/Users/johnm/3D/CUBOTino_venv/lib/python3.8/site-packages/twophase/symmetries.py", line 222, in <module>
    flipslice_rep.fromfile(fh, N_FLIPSLICE_CLASS)
EOFError: read() didn't return enough bytes
>>> 
>>> 
```
I recreated the twophase/* files as per https://github.com/hkociemba/RubiksCube-TwophaseSolver and there are some size differences
```
(CUBOTino_venv) porta-mac:PC_files johnm$ mv twophase/ twophase.orig
(CUBOTino_venv) porta-mac:PC_files johnm$ mkdir twophase
(CUBOTino_venv) porta-mac:PC_files johnm$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import cv2
>>> import twophase.solver as sv
On the first run, several tables will be created. This takes about 1/2 hour or longer (depending on the hardware).
All tables are stored in /Users/johnm/3D/CUBOTino_base_version/PC_files/twophase
...

porta-mac:PC_files johnm$ diff twophase.orig/ twophase/
Binary files twophase.orig/fs_rep and twophase/fs_rep differ
Binary files twophase.orig/phase1_prun and twophase/phase1_prun differ
Binary files twophase.orig/phase2_prun and twophase/phase2_prun differ

porta-mac:PC_files johnm$ ls -l */fs_rep */phase1_prun */phase2_prun
-rw-r--r--  1 johnm  staff    257720  9 Oct 20:40 twophase.orig/fs_rep
-rw-r--r--  1 johnm  staff  35227104 27 Oct 12:55 twophase.orig/phase1_prun
-rw-r--r--  1 johnm  staff  27901440 27 Oct 12:55 twophase.orig/phase2_prun
-rw-r--r--  1 johnm  staff    515440 12 Nov 16:38 twophase/fs_rep
-rw-r--r--  1 johnm  staff  70454208 12 Nov 17:16 twophase/phase1_prun
-rw-r--r--  1 johnm  staff  55802880 12 Nov 17:17 twophase/phase2_prun
```
Module loads now
```
>>> import twophase.solver
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading corner sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
>>> 
```

**Comment by AndreaFavero71** [comment]
Hi John, thank you for the feedback.
I'm glad you have solved the problem in your system.
I'm not well educated in IT, and I don't understand where the problem is...

**If I check the size of those files in a Raspberry Pi OS (working robot):**
pi@cubotino:~/cubotino/src $ ls -l */fs_rep */phase1_prun */phase2_prun
-rw-r--r-- 1 pi pi   257720 Aug  7 12:46 twophase/fs_rep
-rw-r--r-- 1 pi pi 35227104 Aug  7 12:47 twophase/phase1_prun
-rw-r--r-- 1 pi pi 27901440 Aug  7 12:47 twophase/phase2_prun

**and  the size of those files in Windows 10 (working GUI):**
(cubotino_new) D:\CUBOTino_base_version\PC_files\twophase>dir *fs_rep *phase1_prun *phase2_prun
Directory di D:\CUBOTino_base_version\PC_files\twophase
09/10/2022  07:28           257.720 fs_rep
08/10/2022  14:38        35.227.104 phase1_prun
08/10/2022  14:37        27.901.440 phase2_prun
               3 File     63.386.264 byte

**The files size:**
- is exactly the same between the two systems of mine
- obviously the same of your first installation
- and perfectly half size of your newer files creation


I really don't have clues about the reason for this problem, perhaps you can help me out
Regards
Andrea

**Comment by jm493** [comment]
`twophase` passes pre-calculated data using array.fromfile / array.tofile
https://docs.python.org/3/library/array.html doesn't have any warnings but
https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html says

> Do not rely on the combination of tofile and [fromfile](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html#numpy.fromfile) for data storage, as the binary files generated are not platform independent. In particular, no byte-order or data-type information is saved.

Given that both of us have `RubikTwoPhase 1.0.9` I presume `N_FLIPSLICE_CLASS` = 64430 (from defs.py and used in symmetries.py:222)
and that is must then be platform differences are causing the tofile's to be different sizes for only 3 out of 19 saved arrays.

**Comment by jm493** [comment]
The 3 different files are each twice as big.
These 3 files are used for arrays that are the only ones initialised as `ar.array('L', ...)`
https://docs.python.org/3/library/array.html says for 'L' -- Minimum size in bytes = 4.

> The actual representation of values is determined by the machine architecture (strictly speaking, by the C implementation). The actual size can be accessed through the itemsize attribute.

Testing on macOS (from symmetries.py:168)
```
$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> N_FLIPSLICE_CLASS = 64430
>>> flipslice_rep = ar.array('L', [0] * N_FLIPSLICE_CLASS)
>>> print(flipslice_rep.itemsize)
8
>>> 
```
*BINGO*.  'L' uses size 8, not 4.
Can you try some other platforms??

**Comment by AndreaFavero71** [comment]
Hi John,
Thank you to sorting out this issue :-)

I confirm what you already knew...

**In  windows 10:**
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> print(ar.array('L', [0]).itemsize)
4
>>>


**and same results in Raspberry Pi OS:**
Python 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> print(ar.array('L', [0]).itemsize)
4
>>> 


This means some of the files in my repo /twophase aren't not compatible in all platforms.
What I can think of, to make life easier to others: If you let me have your /twophase, I could add a /twophase_macOS folder al let user to rename according to their sytem.
What do you think?
Do you have better ideas (apart letting everyone build those table files)?
In case: andrea.favero71@gmail.com
Regards
Andrea

**Comment by jm493** [comment]
These 3 files are big for me to email them, and for you to add to everyone's distribution ...

I wrote a little script `padlong` that pads L's from 4 to 8 bytes
```
#!/usr/bin/env python
# Pad an array.tofile(f) of unsigned long 'L' from 4-byte to 8-byte
# ref https://docs.python.org/3/library/array.html
#   uses Python 3.8 Walrus operator :=

def padlong(fn1, fn2):

    f1 = open(fn1, "rb")
    f2 = open(fn2, "wb")

    pad = bytes(4)

    while buf := f1.read(4):
       f2.write(buf)
       f2.write(pad)   # add extra zero bytes

    f1.close()
    f2.close()

import array as ar
itemsize = ar.array('L', [0]).itemsize

if itemsize == 4:
    print('No need to pad long integers in supplied files')
else:
    print('Size of unsigned long L is {}'.format(itemsize))
    padlong("twophase.orig/fs_rep", "twophase.macOS/fs_rep")
    padlong("twophase.orig/phase1_prun", "twophase.macOS/phase1_prun")
    padlong("twophase.orig/phase2_prun", "twophase.macOS/phase2_prun")
```
That would allow you to just package and ship 4-byte L files, and allow users to pad the 3 files they need to change.

For reference, here are md5sums for my files.
Can you re-create them (change the if) ?
```
$ md5sum twophase.macOS/*
d87f409ef7745160ad27e87f7c652db6  twophase.macOS/fs_rep
e364c007998f0073e676034b9d5514df  twophase.macOS/phase1_prun
cea0bef0fd51fbb04bebaee03aa6f728  twophase.macOS/phase2_prun
```

**Comment by AndreaFavero71** [comment]
Hi John,
Tried only on Windows 10:  The script works and it's also fast :-)

**Checksum looks as per your files:**
MD5 hash di fs_rep:
d87f409ef7745160ad27e87f7c652db6

MD5 hash di phase1_prun:
e364c007998f0073e676034b9d5514df

MD5 hash di phase2_prun:
cea0bef0fd51fbb04bebaee03aa6f728

**file size is as per your files:**
13/11/2022  23:41           515.440 fs_rep
13/11/2022  23:41        70.454.208 phase1_prun
13/11/2022  23:41        55.802.880 phase2_prun

Thank you for the great help.
Coming days I can add the script to the repo, and update the instructions;
Alternatively you can make a PR and I'll only take care of the iunstructions: As you prefer.
Regards
Andrea

**Comment by jm493** [comment]
I'll let you add the script and update the instructions.

PS. Would using `'I'` work instead of `'L'` to give 4 bytes of storage everywhere?
Or, is there anywhere where twophase could be run where unsigned int is only 2 bytes??
Or, change twophase to test, and then conditionally use `'I'` or `'L'`

On macOS:
```
(CUBOTino_venv) porta-mac:PC_files johnm$ python
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> for t in 'BHILQ':
...   print(t, ar.array(t, [0]).itemsize)
... 
B 1
H 2
I 4
L 8
Q 8
>>> 
```

**Comment by jm493** [comment]
Trying "Ubuntu 22.04.1 LTS" on a Centrino2 vPro
```
sudo apt install pip virtualenv
virtualenv CUBOTino_venv
source CUBOTino_venv/bin/activate
pip install opencv-python
pip install pyserial
pip install RubikTwoPhase
cd CUBOTino_base_version/PC_files/
pip list
Package       Version
------------- --------
numpy         1.23.4
opencv-python 4.6.0.66
pip           22.0.2
pyserial      3.5
RubikTwoPhase 1.0.9
setuptools    59.6.0
wheel         0.37.1

(CUBOTino_venv) johnm@porta-pc:~/3D/CUBOTino_base_version/PC_files$ python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> for t in 'BHILQ':
...   print(t, ar.array(t, [0]).itemsize)
... 
B 1
H 2
I 4
L 8
Q 8
>>> 
```
Original 4-byte twophase files didn't load.  After running "padlong", the 8-byte files loaded.

**Comment by AndreaFavero71** [comment]
Hi John,
I can see Mr. Kociemba has used array 'I', 'B' and 'L': There must be a reason to differentiate them, yet I havent study the twophase library implementation in such detail.

In my Windows 10:
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import array as ar
>>> for t in 'BHILQ':
...   print(t, ar.array(t, [0]).itemsize)
...
B 1
H 2
I 4
L 4
Q 8
>>>

I'll add your script to the repo with related info in the instructions.
Thank you again
Andrea

**Comment by AndreaFavero71** [comment]
Hi John,
it took me long

My proposal would be to have the below script saved as an independent python file, into /src folder, and to call it from Cubotino_GUI before importing the solver library.
I'll anyhow explain in the instruction to run this script before testing the solver import, yet not many read the instructions :-)

I'm still a rather basic programmer, and not concise...
I've slightly changed padlong to tollerate older python versions.
Please let me have your notes
Thank you
Andrea

```
#!/usr/bin/env python
# Pad an array.tofile(f) of unsigned long 'L' from 4-byte to 8-byte
# ref https://docs.python.org/3/library/array.html


def adapt_file(fn, suffix, fldr, fldr1, fldr2):
    """checks if fn exists in folder1.
       Makes folder2 if it does not exist.
       Copy fname+suffix in folder2 (backup copy of original file) if not exists:
       Checks if fname in folder 1 is padded to 8 bytes, if not it is done."""
    
    result = True
    fn_crnt = os.path.join(fldr, fldr1, fn)                # current file in fldr1
    fn_new = os.path.join(fldr, fldr1, fldr2, fn + suffix) # file new name in fldr2
    folder = os.path.join(fldr, fldr1, fldr2)              # folder to store the original (renamed) file 
    
    if not os.path.exists(folder):    # case folder fldr2 does not exist
        os.makedirs(folder)           # folder fldr2 is made
    
    if not os.path.isfile(fn_new):    # case file new name does not exists in folder fldr2
        # this is done only once at the first time
        os.rename(fn_crnt, fn_new)    # original file in fldr1 is renamed to new file name in fldr2
        padlong(fn_new, fn_crnt)      # pad 8 bytes orig file (renamed, in fldr2) and save it into orig fname in fldr1
    
    else:                             # case file new name does not exists in folder (fldr2)
        if check_files_size(fn_crnt, fn_new):  # case current file in fldr1 is 2 times bigger than file new name in fldr2 
            print('File already padded to 8 bytes:', fn_crnt)  # feedback is printed to the terminal
            pass                      # no further actions             
        else:                         # case current file in fldr1 is not padded 8 bytes
            result = padlong(fn_new, fn_crnt)  # pad 8 bytes orig file (renamed, in fldr2) and save it into orig fname in fldr1
    
    return result
        



def check_files_size(fn1, fn2):
    """checks if one file is double the size of the other"""
    
    fn1_size = os.path.getsize(fn1)                         # files size file fn1
    fn2_size = os.path.getsize(fn2)                         # files size file fn2
    if max(fn1_size,fn2_size)/min(fn1_size,fn2_size) == 2:  # case max == 2 * min file size
        return True                                         # returns true
    
    else:              # case max not equal 2 * min file size
        print('\n\nERROR: please check the instructions for macOS or Ubuntu at:')
        print('https://github.com/AndreaFavero71/CUBOTino_base_version/tree/main/PC_files/twophase\n')
        return False   # returns false




def padlong(fn1, fn2):
    """Pads extra 4 bytes (all bits at 0`) every 4 bytes of the original file (fn1).
        Issue investigated and solution dentified by jm493."""

    print('padding from 4 to 8 bytes arrays in file:', fn2)
    
    try:
        f1 = open(fn1, "rb")
        f2 = open(fn2, "wb")
        pad = bytes(4)
        buf = f1.read(4)
        while buf :
            f2.write(buf)
            f2.write(pad)     # add extra zero bytes
            buf = f1.read(4)
        f1.close()
        f2.close()
    
    except:
        print('\n\nERROR: please check the instructions for macOS or Ubuntu at:')
        print('https://github.com/AndreaFavero71/CUBOTino_base_version/tree/main/PC_files/twophase\n')

        



import os                               # operating system dependent functionalities module
import array as ar                      # array object generator module
itemsize = ar.array('L', [0]).itemsize  # actual size of values is machine architecture dependent

if itemsize == 4:                       # case the machine uses 4 bytes per array value
#         print('No need to pad long integers in supplied files') # feedback is printed to the terminal
    pass                                # no actions needed                     

else:                                   # case the machine uses 8 bytes per array value
    fnames = ('fs_rep', 'phase1_prun', 'phase2_prun') # files of interest
    suffix = '_orig'                    # string suffixi to alter the original fnames
    folder = os.getcwd()                # folder of current script
    folder1 = 'twophase'                # one level down folder
    folder2 = 'orig_files'              # two levels down folder
    
    fn = os.path.join(folder, folder1, 'padded_files.txt') # check file name
    if not os.path.isfile(fn):          # case check file does not exists in folder folder//folder1

        result = True                   # true is assigned to result variable    
        for fname in fnames:            # iteration over the files names
            result = adapt_file(fname, suffix, folder, folder1, folder2)  # function to adapt the files
            if not result:              # case the function return is false
                break                   # iteration is terminated
        
        if result:                      # case the files adaptation went well
            import datetime as dt       # import the datetime module
            timestamp = dt.datetime.now().strftime('%Y%m%d_%H%M%S')        # date_time variable
            text = timestamp + ' padded to 8 bytes files: ' + str(fnames)  # text to save in file
            fn = os.path.join(folder, folder1, 'padded_files.txt')         # file name to track the adapted files action
            with open(fn, 'w') as f:                                       # opens a text file in writing mode       
                f.write(text)                                              # writes text in file and closes it

    else:                                # case check file exists in folder folder//folder1
#         print('files in /twophase folder have right byte size') # feedback is printed to the terminal
        pass
```

**Comment by jm493** [comment]
In other news ...

@hkociemba has fixed this problem on Nov 16, 2022
https://github.com/hkociemba/RubiksCube-TwophaseSolver/commits/master

Here it is not working with 4-byte data files; upgrade RubikTwoPhase to version 1.1.1; works again.

```
(CUBOTino_venv) porta-mac:PC_files johnm$ python3
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import twophase.solver  as sv
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnm/3D/CUBOTino_venv/lib/python3.8/site-packages/twophase/solver.py", line 5, in <module>
    import twophase.symmetries as sy
  File "/Users/johnm/3D/CUBOTino_venv/lib/python3.8/site-packages/twophase/symmetries.py", line 222, in <module>
    flipslice_rep.fromfile(fh, N_FLIPSLICE_CLASS)
EOFError: read() didn't return enough bytes
>>> ^D
(CUBOTino_venv) porta-mac:PC_files johnm$ pip3 list --outdated
Package       Version Latest Type
------------- ------- ------ -----
RubikTwoPhase 1.0.9   1.1.1  wheel
...
(CUBOTino_venv) porta-mac:PC_files johnm$ pip install --upgrade RubikTwoPhase
Requirement already satisfied: RubikTwoPhase in /Users/johnm/3D/CUBOTino_venv/lib/python3.8/site-packages (1.0.9)
Collecting RubikTwoPhase
  Downloading RubikTwoPhase-1.1.1-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.9/53.9 kB 1.6 MB/s eta 0:00:00
Installing collected packages: RubikTwoPhase
  Attempting uninstall: RubikTwoPhase
    Found existing installation: RubikTwoPhase 1.0.9
    Uninstalling RubikTwoPhase-1.0.9:
      Successfully uninstalled RubikTwoPhase-1.0.9
Successfully installed RubikTwoPhase-1.1.1

(CUBOTino_venv) porta-mac:PC_files johnm$ python3
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import twophase.solver  as sv
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading corner sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
loading phase2_edgemerge table...

>>> cubestring = 'DUUBULDBFRBFRRULLLBRDFFFBLURDBFDFDRFRULBLUFDURRBLBDUDL'
>>> sv.solve(cubestring,19,2)
'L3 U1 B1 R2 F3 L1 F3 U2 L1 U3 B3 U2 B1 L2 F1 U2 R2 L2 B2 (19f)'
>>> 
```

I used RubikTwoPhase 1.1.1 to generate a new set of data files, and they are the same as the data files that came with CUBOTino.

**Comment by AndreaFavero71** [comment]
Hi John,
please confirm my understanding, as I'm not sure to catch you correctly
1) By modifying the arrays to 8 bytes it does not work
2) By updating the solver to the latest version it works.
Correct?

Thank you
Andrea

Il giorno ven 18 nov 2022 alle ore 06:09 John Mann ***@***.***>
ha scritto:

**Comment by jm493** [comment]
Andrea,
Sorry for not being clear.
1) Unmodified arrays, original RubikTwoPhase 1.0.9, it does not work on macOS
2) Unmodified arrays, upgraded RubikTwoPhase 1.1.1, it works.

I am not using any modified array files.
It is not needed to pad the files any more (assuming people new install / upgrade to RubikTwoPhase 1.1.1).
In fact, reading padded files using RubikTwoPhase 1.1.1 will lead to the wrong result.

John

**Comment by AndreaFavero71** [comment]
Hi John,
I'm not quick on grasping stuff.
I'm happy to read the problem has been solved at the source, that's always the best solution.
Thank you for your digging into this, and to have 'forced' me to learn some new things, like the Walrus operator :-).
I'll anyhow add a note to the instructions to update the solver to 1.1.1 when macOS and Ubuntu.
Please drop a comment when you'll have an up and running Cubotino :-)
Kind regards
Andrea

**Comment by AndreaFavero71** [comment]
For the readers
In case you experience the error "import twophase.solver "EOFError: read() didn't return enough bytes" with a macOS or Ubuntu, update RubikTwoPhase to version 1.1.1
